config/routes.rb
Rails.application.routes.draw do

  
  get '/get-sections' => 'students#get_sections'
  get '/save-grade' => 'grades#save_grade'

  resources :sections
  resources :rooms
  get '/logout' => 'home#logout'
  post '/login' => 'home#login'
  resources :teachers
  resources :positions
  resources :events
  resources :users
  resources :schedules
  resources :subjects
  get '/schedules/student/:year_level_id/:section_id' => 'schedules#student_show'
  post '/change-password' => 'users#change_password'
  get '/change-password' => 'home#change_password'
  get '/grades' => 'grades#index'
  get '/grades/show/:id' => 'grades#show'
  get '/main' => 'home#main'
  get '/schedule' => 'home#schedule'
  get '/students-main' => 'home#students_main'
  post '/pay' => 'payments#pay'
  get '/payform/:student_id' => 'payments#payform'
  get '/payments/print/:or_number' => 'payments#print'
  get '/payments' => 'payments#index'
  get '/payments/:student_id' => 'payments#history'
  get '/get-payment' => 'payments#get_payment'
  
  resources :students
  root 'home#index'
  

end

app/models/student.rb
# class Student < ActiveRecord::Base
#     has_many :student_year_sections
#     has_many :payments

#     def self.index_fields
#         joins(:student_year_sections)
#          .select("students.id, 
#                           students.student_id, 
#                           students.fname, 
#                           students.mname, 
#                           students.lname, 
#                           students.address,
#                           students.status, max(student_year_sections.school_year) school_year")
#         .group("students.id")
                            
#     end
# end
class Student < ActiveRecord::Base
    has_many :student_year_sections
    has_many :payments

    def self.index_fields
        joins(:student_year_sections => [:year_level])
         .select("students.id, 
                          students.student_id, 
                          students.fname, 
                          students.mname, 
                          students.lname, 
                          students.address,
                          students.status, 
                          year_levels.description grade,
                          student_year_sections.year_level_id,
                          student_year_sections.section_id")
                            
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_filter :admin_access_only, except: [:show, :index]
  before_filter :check_access

  # GET /students
  # GET /students.json
  def index
    if session[:user]["access"] == 1
      @students = Student.index_fields.paginate(:page => params[:page], :per_page => 20)
      if params[:txt_search]
          @students = Student.index_fields.where("students.fname ilike ? or students.lname ilike ?", "#{params[:txt_search]}%", "#{params[:txt_search]}%").paginate(:page => params[:page], :per_page => 20) if params[:searchby] == "fname"
      end
    elsif session[:user]["access"] == 2
      teacher_id = Teacher.find_by_user_id(session[:user]["id"]).id
      handled = Schedule.select("year_level_id, section_id").distinct.where("teacher_id = ? and description not in ('flag ceremony', 'lunch break', 'recess')", teacher_id)
      @students = Student.index_fields.where(:student_year_sections => {:year_level_id => handled.collect {|a| a.year_level_id}, :section_id => handled.collect {|a| a.section_id}}).paginate(:page => params[:page], :per_page => 20)
      if params[:txt_search]
          @students = Student.index_fields.where("students.fname ilike ? or students.lname ilike ?", "#{params[:txt_search]}%", "#{params[:txt_search]}%").where(:student_year_sections => {:year_level_id => handled.collect {|a| a.year_level_id}, :section_id => handled.collect {|a| a.section_id}}).paginate(:page => params[:page], :per_page => 20) if params[:searchby] == "fname"
      end
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @student_year_section = StudentYearSection.where(student_id: @student.id).first
    @user = User.where(id: @student.user_id).first
  end

  # GET /students/new
  def new
    @student = Student.new
    @user = User.new
    autogenerate_id
  end

  # GET /students/1/edit
  def edit
    @student_year_section = StudentYearSection.where(student_id: @student.id).first
    @user = User.where(id: @student.user_id).first
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)
    @user = User.new(user_params)
    respond_to do |format|
      @user.save
      if @student.save
        @student.update(user_id: @user.id)
        StudentYearSection.create(student_id: @student.id, year_level_id: params[:year_level][:id], section_id: params[:section][:id])
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        StudentYearSection.where(student_id: @student.id).first.update(year_level_id: params[:year_level][:id], section_id: params[:section][:id])
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def autogenerate_id
    year_now = Time.now.year.to_s
    get_last_student_id = Student.where("student_id ilike ?", year_now + "-AS-%").count + 1
    @student_id = year_now + "-AS-" + get_last_student_id.to_s.rjust(4, '0')
  end

  def get_sections
    render :inline => '<%= options_from_collection_for_select(Section.where(:year_level_id => ' + params[:grade] + '), :id, :description) %>'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:fname, :mname, :lname, :birthdate, :gender, :address, :birthplace, :religion, :status, :student_id, 
      :father_name, :father_birthdate, :father_address, :father_occupation, :father_contact, 
      :mother_name, :mother_birthdate, :mother_address, :mother_occupation, :mother_contact)
    end

    def user_params
      params.require(:user).permit(:user_name, :user_pass, :access, :status)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
<% if @student.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>
	<ul>
		<% @student.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="panel panel-default">
	<div class="panel-heading">Student's Profile</div>
	<div class="panel-body">
		<div class="row">
			<div class="col-sm-4">
				<label for="student_student_id">Student ID</label>
				<input class="form-control" type="text" name="student[student_id]" id="student_student_id" value="<%= params[:id] ? @student.student_id : '' %>">
			</div>
			<div class="col-sm-2">
				<label for="year_level_id">Grade / Year Level</label>
				<%= select("year_level", "id", YearLevel.all.collect {|s| [s.description, s.id]}, {:selected => params[:id] ? begin @student_year_section.year_level_id rescue raise "No Year Level specified" end : 0}, :class => "form-control")%>
			</div>
			<div class="col-sm-2">
				<label for="student_other_info_section">Section</label>
				<%= select("section", "id", Section.all.collect {|s| [s.description, s.id]}, {:selected => params[:id] ? begin @student_year_section.section_id rescue raise "No Section specified" end : 0}, :class => "form-control")%>
			</div>
			<div class="col-sm-2">
				<%= f.label :status %>
				<select id="student_status" class="form-control" name="student[status]">
					<option>Continuing</option>
					<option <%= "selected" if @student.status == "Drop" %>>Drop</option>
					<option <%= "selected" if @student.status == "Transfer" %>>Transfer</option>
					<option <%= "selected" if @student.status == "Returning" %>>Returning</option>
					<option <%= "selected" if @student.status == "Stop" %>>Stop</option>
				</select>
			</div>
			<div class="col-sm-2">
				<label for="school_year">School Year</label>
				<select id="school_year" class="form-control" name="school_year">
					<option>2017-2018</option>
					<option>2016-2017</option>
					<option>2015-2016</option>
					<option>2014-2015</option>
				</select>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-4">
				<%= f.label "Last Name" %>
				<%= f.text_field :lname, class: "form-control", :required => true %>
			</div>
			<div class="col-sm-4">
				<%= f.label "First Name" %>
				<%= f.text_field :fname, class: "form-control", :required => true %>
			</div>
			<div class="col-sm-4">
				<%= f.label "Middle Name" %>
				<%= f.text_field :mname, class: "form-control" %>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-4">
				<%= f.label :birthdate %>
				<%= f.date_field :birthdate, class: "form-control", :required => true %>
			</div>
			<div class="col-sm-4">
				<%= f.label :gender %>
				<select class="form-control" name="student[gender]">
					<option>Male</option>
					<option>Female</option>
				</select>
			</div>
			<div class="col-sm-4">
				<%= f.label :religion %>
				<select class="form-control" name="student[religion]">
					<option>Roman Catholic</option>
					<option <%= 'selected' if @student.religion == 'Iglesia Ni Cristo' %>>Iglesia Ni Cristo</option>
					<option <%= 'selected' if @student.religion == 'Muslim' %>>Muslim</option>
					<option <%= 'selected' if @student.religion == 'Mormon' %>>Mormon</option>
					<option <%= 'selected' if @student.religion == "Born Again Christian" %>>Born Again Christian</option>
				</select>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-6">
				<%= f.label :birthplace %>
				<%= f.text_field :birthplace, class: "form-control", :required => true %>
			</div>
			<div class="col-sm-6">
				<%= f.label :address %>
				<%= f.text_field :address, class: "form-control" %>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-6">
				<%= f.label :username %>
				<input class="form-control" type="text" name="user[user_name]" id="user_user_name" value="<%= @user.user_name %>" required>
			</div>
			<div class="col-sm-6">
				<%= f.label :password %>
				<input class="form-control" type="password" name="user[user_pass]" id="user_user_pass" value="<%= @user.user_pass %>">
				<input class="form-control" type="hidden" name="user[access]" value="3">
				<input class="form-control" type="hidden" name="user[status]" id="user_status" value="Active">
			</div>
		</div>
	</div>
</div>
<div class="row">
<!-- BEGIN father's profile -->
<div class="col-sm-6">
  <div class="panel panel-default">
    <div class="panel-heading">Father's Profile</div>
    <div class="panel-body">
      <div class="row">
        <div class="col-sm-12">
          <label for="student_father_name">Name</label>
          <%= f.text_field :father_name, class: "form-control", :required => true %>
        </div>
        <div class="col-sm-12">
          <label for="student_father_birthdate">Birthdate</label>
          <%= f.date_field :father_birthdate, class: "form-control", :required => true %>
        </div>
        <div class="col-sm-12">
          <label for="student_father_address">Address</label>
          <%= f.text_field :father_address, class: "form-control", :required => true %>
        </div>
        <div class="col-sm-12">
          <label for="student_father_occupation">Occupation</label>
          <%= f.text_field :father_occupation, class: "form-control", :required => true %>
        </div>
        <div class="col-sm-12">
          <label for="student_father_contact">Contact Number</label>
          <%= f.text_field :father_contact, class: "form-control", :required => true %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- END father's profile -->
<!-- BEGIN mother's profile -->
<div class="col-sm-6">
  <div class="panel panel-default">
    <div class="panel-heading">Mother's Profile</div>
    <div class="panel-body">
      <div class="row">
        <div class="col-sm-12">
          <label for="student_mother_name">Name</label>
          <%= f.text_field :mother_name, class: "form-control", :required => true %>
        </div>
        <div class="col-sm-12">
          <label for="student_mother_birthdate">Birthdate</label>
          <%= f.date_field :mother_birthdate, class: "form-control", :required => true %>
        </div>
        <div class="col-sm-12">
          <label for="student_mother_address">Address</label>
          <%= f.text_field :mother_address, class: "form-control", :required => true %>
        </div>
        <div class="col-sm-12">
          <label for="student_mother_occupation">Occupation</label>
          <%= f.text_field :mother_occupation, class: "form-control", :required => true %>
        </div>
        <div class="col-sm-12">
          <label for="student_mother_contact">Contact Number</label>
          <%= f.text_field :mother_contact, class: "form-control", :required => true %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- END mother's profile -->
</div>
<div class="row" id="div-btn-save">
	<div class="col-sm-12">
		<button class="btn btn-primary" type="submit">
		<span class="glyphicon glyphicon-saved"></span> Save
		</button>
		<a class="btn btn-primary" href="/students">
        <span class="glyphicon glyphicon-arrow-left"></span> Back
    </a>
	</div>
</div>
<% end %>
<script>
	$(document).ready(function(){
	  $("#student_status").change(function() {
	    var status = $("#student_status option:selected").val();
	    $("#user_status").val(status);
	  });
	});
</script>

app/views/students/edit.html.erb
<div id="form-student" class="container-fluid"><div class="row"><div class="col-sm-10 col-sm-offset-1">
<h1 class="page-header">Editing Student</h1>
<%= render 'form' %>
</div></div></div>
<script>
	$(document).ready(function() {
		$("#section_id").val(<%= @student_year_section.section_id %>);
	})
</script>

app/views/students/index.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
            <h1 class="page-header">Students Information</h1>
            <div class="row page-header" style="margin-bottom: 10px;">
              <form>
              <div class="col-sm-3 hidden">
               <label>Search by:</label>
                <select class="form-control" name="searchby">
                  <option value="fname">First Name</option>
                  <option value="lname" <%= "selected" if params[:searchby] == "lname" %>>Last Name</option>
                  <option value="year_level" <%= "selected" if params[:searchby] == "year_level" %>>Year Level</option>
                </select>
              </div>
              <div class="col-sm-3">
                <label>Search text:</label>
                <input type="text" class="form-control" name="txt_search" value="<%= params[:txt_search] if params[:txt_search] %>">
              </div>
              <div class="col-sm-2" style="margin-top: 25px;">
                <button class="btn btn-primary" type="submit">
                    <span class="glyphicon glyphicon-search"></span> Search
                </button>
              </div>
              </form>
              <div class="col-sm-7" style="margin-top: 25px;">
              <% if session[:user]["access"] == 1 %>
                  <a class="btn btn-primary pull-right" href="/students/new">
                    <span class="glyphicon glyphicon-plus"></span> Add Student
                  </a>
                <% end %>
              </div>
            </div>
            <table class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th>Student ID</th>
                  <th>First name</th>
                  <th>Middle name</th>
                  <th>Last name</th>
                  <th>Address</th>
                  <th>Status</th>
                  <th>Grade</th>
                  <th colspan="2"></th>
                </tr>
              </thead>
              <tbody>
                <% @students.each do |student| %>
                  <tr>
                    <td><%= student.student_id %></td>
                    <td><%= student.fname.titleize %></td>
                    <td><%= student.mname.titleize %></td>
                    <td><%= student.lname.titleize %></td>
                    <td><%= student.address.titleize %></td>
                    <td><%= student.status %></td>
                    <td><%= student.student_year_sections.first.year_level.description %></td>
                    <td><%= link_to student, :class => "btn btn-primary btn-sm" do %>
                          <span class="glyphicon glyphicon-eye-open"></span> View
                        <% end %>
                    </td>
                    <% if session[:user]["access"] == 1 %>
                    <td>
                        <%= link_to edit_student_path(student), :class => "btn btn-primary btn-sm" do %>
                          <span class="glyphicon glyphicon-pencil"></span> Edit
                        <% end %>
                    </td>
                    <% end %>
                    <td class="hidden"><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <br>
            <div class="row text-center">
              <%= will_paginate @students %>
              Result: <%= @students.count %>
            </div>
        </div>
    </div>
</div>

app/views/students/new.html.erb
<div id="form-student" class="container-fluid"><div class="row"><div class="col-sm-10 col-sm-offset-1">
<h1 class="page-header">New Student</h1>
<%= render 'form' %>
</div></div></div>

app/views/students/show.html.erb
<div id="form-student" class="container-fluid"><div class="row"><div class="col-sm-10 col-sm-offset-1">
<% if notice %>
  <div class="alert alert-success"><%= notice %></div>
<% end %>
<h1 class="page-header">Student Information</h1>
<%= render 'form' %>
<a class="btn btn-primary" href="<%= session[:user]["access"] == 1 || session[:user]["access"] == 2 ? '/students' : '/students-main' %>">
    <span class="glyphicon glyphicon-arrow-left"></span> Back</a>
</div></div></div>
<script>
  $(document).ready(function() {
    $(".form-control").prop("disabled", true);
    $("#div-btn-save").hide();
  });
</script>