config/routes.rb
Rails.application.routes.draw do

  
  get '/get-sections' => 'students#get_sections'
  get '/save-grade' => 'grades#save_grade'

  resources :sections
  resources :rooms
  get '/logout' => 'home#logout'
  post '/login' => 'home#login'
  resources :teachers
  resources :positions
  resources :events
  resources :users
  resources :schedules
  resources :subjects
  get '/schedules/student/:year_level_id/:section_id' => 'schedules#student_show'
  post '/change-password' => 'users#change_password'
  get '/change-password' => 'home#change_password'
  get '/grades' => 'grades#index'
  get '/grades/show/:id' => 'grades#show'
  get '/main' => 'home#main'
  get '/schedule' => 'home#schedule'
  get '/students-main' => 'home#students_main'
  post '/pay' => 'payments#pay'
  get '/payform/:student_id' => 'payments#payform'
  get '/payments/print/:or_number' => 'payments#print'
  get '/payments' => 'payments#index'
  get '/payments/:student_id' => 'payments#history'
  get '/get-payment' => 'payments#get_payment'
  
  resources :students
  root 'home#index'
  

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :year_level
  belongs_to :section
  belongs_to :teacher

  def self.index_fields
    joins(:position, :subject, :room).
    select("teachers.id, teachers.teacherid, teachers.first_name,
            teachers.last_name,
            positions.description pos,
            subjects.description sub,
            rooms.description rm")
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:edit, :update, :destroy]
  before_filter :admin_access_only, only: [:index, :new]
  before_filter :check_access

  # GET /schedules
  # GET /schedules.json
  def index
    #@schedules = Schedule.paginate(:page => params[:page], :per_page => 20)
    @teachers = Teacher.index_fields.paginate(:page => params[:page], :per_page => 20)
    if params[:txt_search]
        @teachers = Teacher.index_fields.where("teachers.first_name ilike ?", "#{params[:txt_search]}%").paginate(:page => params[:page], :per_page => 20) if params[:searchby] == "fname"
        @teachers = Teacher.index_fields.where("teachers.last_name ilike ?", "#{params[:txt_search]}%").paginate(:page => params[:page], :per_page => 20) if params[:searchby] == "lname"
    end
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
    sy = Time.now.year.to_s + "-" + (Time.now + 1.year).year.to_s
    if params[:school_year]
      sy = params[:school_year]
    end

    @sched1 = Schedule.where(:teacher_id => params[:id], :description => "flag ceremony", :school_year => sy).select("schedules.schedule_time")
    @sched2 = Schedule.joins(:year_level, :section).where(:teacher_id => params[:id], :description => "2", :school_year => sy).select("schedules.schedule_time, year_levels.description grade, sections.description sec")
    @sched3 = Schedule.joins(:year_level, :section).where(:teacher_id => params[:id], :description => "3", :school_year => sy).select("schedules.schedule_time, year_levels.description grade, sections.description sec")
    @sched4 = Schedule.where(:teacher_id => params[:id], :description => "recess", :school_year => sy).select("schedules.schedule_time")
    @sched5 = Schedule.joins(:year_level, :section).where(:teacher_id => params[:id], :description => "5", :school_year => sy).select("schedules.schedule_time, year_levels.description grade, sections.description sec")
    @sched6 = Schedule.joins(:year_level, :section).where(:teacher_id => params[:id], :description => "6", :school_year => sy).select("schedules.schedule_time, year_levels.description grade, sections.description sec")
    @sched7 = Schedule.joins(:year_level, :section).where(:teacher_id => params[:id], :description => "7", :school_year => sy).select("schedules.schedule_time, year_levels.description grade, sections.description sec")
    @sched8 = Schedule.where(:teacher_id => params[:id], :description => "lunch break", :school_year => sy).select("schedules.schedule_time")
    @sched9 = Schedule.joins(:year_level, :section).where(:teacher_id => params[:id], :description => "9", :school_year => sy).select("schedules.schedule_time, year_levels.description grade, sections.description sec")
    @sched10 = Schedule.joins(:year_level, :section).where(:teacher_id => params[:id], :description => "10", :school_year => sy).select("schedules.schedule_time, year_levels.description grade, sections.description sec")
    @sched11 = Schedule.joins(:year_level, :section).where(:teacher_id => params[:id], :description => "11", :school_year => sy).select("schedules.schedule_time, year_levels.description grade, sections.description sec")
    @sched12 = Schedule.joins(:year_level, :section).where(:teacher_id => params[:id], :description => "12", :school_year => sy).select("schedules.schedule_time, year_levels.description grade, sections.description sec")
    @sched13 = Schedule.joins(:year_level, :section).where(:teacher_id => params[:id], :description => "13", :school_year => sy).select("schedules.schedule_time, year_levels.description grade, sections.description sec")
    
  
    @teacher = Teacher.joins(:position, :subject, :room).
    select("teachers.id, teachers.first_name,
            teachers.last_name,
            positions.description pos,
            subjects.description sub,
            rooms.description rm").find(params[:id])
  end

  def student_show
    sy = Time.now.year.to_s + "-" + (Time.now + 1.year).year.to_s
    if params[:school_year]
      sy = params[:school_year]
    end

    @sched1 = Schedule.where(:description => "flag ceremony", :school_year => sy).select("schedules.schedule_time")
    @sched2 = Schedule.joins(:year_level, :section, :teacher => [:position, :subject, :room]).where(:year_level_id => params[:year_level_id], :section_id => params[:section_id], :description => "2", :school_year => sy).select("schedules.schedule_time, year_levels.description grade, sections.description sec, subjects.description subject, rooms.description room")
    @sched3 = Schedule.joins(:year_level, :section, :teacher => [:position, :subject, :room]).where(:year_level_id => params[:year_level_id], :section_id => params[:section_id], :description => "3", :school_year => sy).select("schedules.schedule_time, year_levels.description grade, sections.description sec, subjects.description subject, rooms.description room")
    @sched4 = Schedule.joins(:year_level, :section, :teacher => [:position, :subject, :room]).where(:year_level_id => params[:year_level_id], :section_id => params[:section_id], :description => "recess", :school_year => sy).select("schedules.schedule_time, year_levels.description grade, sections.description sec, subjects.description subject, rooms.description room")
    @sched5 = Schedule.joins(:year_level, :section, :teacher => [:position, :subject, :room]).where(:year_level_id => params[:year_level_id], :section_id => params[:section_id], :description => "5", :school_year => sy).select("schedules.schedule_time, year_levels.description grade, sections.description sec, subjects.description subject, rooms.description room")
    @sched6 = Schedule.joins(:year_level, :section, :teacher => [:position, :subject, :room]).where(:year_level_id => params[:year_level_id], :section_id => params[:section_id], :description => "6", :school_year => sy).select("schedules.schedule_time, year_levels.description grade, sections.description sec, subjects.description subject, rooms.description room")
    @sched7 = Schedule.joins(:year_level, :section, :teacher => [:position, :subject, :room]).where(:year_level_id => params[:year_level_id], :section_id => params[:section_id], :description => "7", :school_year => sy).select("schedules.schedule_time, year_levels.description grade, sections.description sec, subjects.description subject, rooms.description room")
    @sched8 = Schedule.joins(:year_level, :section, :teacher => [:position, :subject, :room]).where(:year_level_id => params[:year_level_id], :section_id => params[:section_id], :description => "flag ceremony", :school_year => sy).select("schedules.schedule_time, year_levels.description grade, sections.description sec, subjects.description subject, rooms.description room")
    @sched9 = Schedule.joins(:year_level, :section, :teacher => [:position, :subject, :room]).where(:year_level_id => params[:year_level_id], :section_id => params[:section_id], :description => "9", :school_year => sy).select("schedules.schedule_time, year_levels.description grade, sections.description sec, subjects.description subject, rooms.description room")
    @sched10 = Schedule.joins(:year_level, :section, :teacher => [:position, :subject, :room]).where(:year_level_id => params[:year_level_id], :section_id => params[:section_id], :description => "10", :school_year => sy).select("schedules.schedule_time, year_levels.description grade, sections.description sec, subjects.description subject, rooms.description room")
    @sched11 = Schedule.joins(:year_level, :section, :teacher => [:position, :subject, :room]).where(:year_level_id => params[:year_level_id], :section_id => params[:section_id], :description => "11", :school_year => sy).select("schedules.schedule_time, year_levels.description grade, sections.description sec, subjects.description subject, rooms.description room")
    @sched12 = Schedule.joins(:year_level, :section, :teacher => [:position, :subject, :room]).where(:year_level_id => params[:year_level_id], :section_id => params[:section_id], :description => "12", :school_year => sy).select("schedules.schedule_time, year_levels.description grade, sections.description sec, subjects.description subject, rooms.description room")
    @sched13 = Schedule.joins(:year_level, :section, :teacher => [:position, :subject, :room]).where(:year_level_id => params[:year_level_id], :section_id => params[:section_id], :description => "13", :school_year => sy).select("schedules.schedule_time, year_levels.description grade, sections.description sec, subjects.description subject, rooms.description room")
  end
  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    #asdf
    @monday1 = Schedule.new(monday1_params) #flag ceremony
    @monday2 = Schedule.new(monday2_params)
    @monday3 = Schedule.new(monday3_params)
    @monday4 = Schedule.new(monday4_params)
    @monday5 = Schedule.new(monday5_params)
    @monday6 = Schedule.new(monday6_params)
    @monday7 = Schedule.new(monday7_params)
    @monday8 = Schedule.new(monday8_params) #lunch break
    @monday9 = Schedule.new(monday9_params)
    @monday10 = Schedule.new(monday10_params)
    @monday11 = Schedule.new(monday11_params)
    @monday12 = Schedule.new(monday12_params)
    @monday13 = Schedule.new(monday13_params)

    @tuesday1 = Schedule.new(tuesday1_params) #flag ceremony
    @tuesday2 = Schedule.new(tuesday2_params)
    @tuesday3 = Schedule.new(tuesday3_params)
    @tuesday4 = Schedule.new(tuesday4_params)
    @tuesday5 = Schedule.new(tuesday5_params)
    @tuesday6 = Schedule.new(tuesday6_params)
    @tuesday7 = Schedule.new(tuesday7_params)
    @tuesday8 = Schedule.new(tuesday8_params) #lunch break
    @tuesday9 = Schedule.new(tuesday9_params)
    @tuesday10 = Schedule.new(tuesday10_params)
    @tuesday11 = Schedule.new(tuesday11_params)
    @tuesday12 = Schedule.new(tuesday12_params)

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
            <p id="notice"><%= notice %></p>
            <h1 class="page-header">Schedules
            <% if session[:user]["access"] == 1 %>
              <a href="/schedules/new" class="btn btn-primary pull-right">
                  <span class="glyphicon glyphicon-calendar"></span> Add Schedule
              </a>
            <% end %>
            </h1>
                
              <div class="row" style="margin-bottom: 10px;">
                    <form>
                      <div class="col-sm-3">
                      <label>Search by:</label>
                        <select class="form-control" name="searchby">
                          <option value="fname">First Name</option>
                          <option value="lname" <%= "selected" if params[:searchby] == "lname" %>>Last Name</option>
                        </select>
                      </div>
                      <div class="col-sm-3">
                        <label>Search text:</label>
                        <input type="text" class="form-control" name="txt_search" value="<%= params[:txt_search] if params[:txt_search] %>">
                      </div>
                      <div class="col-sm-2" style="margin-top: 25px;">
                        <button class="btn btn-primary" type="submit">
                            <span class="glyphicon glyphicon-search"></span> Search
                        </button>
                      </div>
                      </form>
              </div>
            <table class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th>First name</th>
                  <th>Last name</th>
                  <th>Position</th>
                  <th>Subject</th>
                  <th>Room</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% @teachers.each do |teacher| %>
                <tr>
                  <td><%= teacher.first_name %></td>
                  <td><%= teacher.last_name %></td>
                  <td><%= teacher.pos %></td>
                  <td><%= teacher.sub %></td>
                  <td><%= teacher.rm %></td>
                  <td>
                    <%= link_to schedule_path(teacher), :class => "btn btn-sm btn-primary" do %>
                      View
                    <% end %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
            <br>
            <div class="row text-center">
              <%= will_paginate @teachers %>
            </div>
        </div>
    </div>
</div>

app/views/schedules/new.html.erb
<div class="container-fluid"><div class="row"><div class="col-sm-10 col-sm-offset-1">
<% if notice %>
  <div class="alert alert-danger"><span class="glyphicon glyphicon-remove"></span> <%= notice %></div>
<% end %>
<h1 class="page-header">New Schedule</h1>
<%= render 'form' %>
</div></div></div>

app/views/schedules/show.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
            <p id="notice"><%= notice %></p>
            <h1 class="page-header">Schedule</h1>
            <form id="school_year_form" method="get" action="/schedules/<%= params[:id] %>" style="width: 150px;">
                <select class="form-control" id="school_year" name="school_year">
                    <% (Time.now + 1.year).year.downto(2014).each do |yr| %>
                    <option <%= 'selected' if params[:school_year] == (yr-1).to_s + "-" + yr.to_s %>><%= (yr-1).to_s + "-" + yr.to_s %></option>
                    <% end %>
                </select>
            </form>
            <div class="panel panel-default" style="margin-top: 20px;">
                <div class="panel-heading"></div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-3">
                            First Name: <strong><%= @teacher.first_name %></strong>
                        </div>
                        <div class="col-sm-3">
                            Last Name: <strong><%= @teacher.last_name %></strong>
                        </div>
                        <div class="col-sm-3">
                            Subject: <strong><%= @teacher.sub %></strong>
                        </div>
                        <div class="col-sm-3">
                            Room: <strong><%= @teacher.rm %></strong>
                        </div>
                    </div>
                </div>
            </div>
            <table class="table table-bordered table-striped">
                <tr>
                    <td><strong>Time</strong></td>
                    <td><strong>Monday</strong></td>
                    <td><strong>Tuesday</strong></td>
                    <td><strong>Wednesday</strong></td>
                    <td><strong>Thursday</strong></td>
                    <td><strong>Friday</strong></td>
                </tr>
                <tr>
                    <td>
                        <% begin %>
                        <%= @sched1.first.schedule_time %>
                        <% rescue %>
                        <% end %>
                    </td>
                    <td>Flag Ceremony</td>
                    <td>Flag Ceremony</td>
                    <td>Flag Ceremony</td>
                    <td>Flag Ceremony</td>
                    <td>Flag Ceremony</td>
                </tr>
                <tr>
                    <td>
                        <% begin %>
                        <%= @sched2.first.schedule_time %>
                        <% rescue %>
                        <% end %>
                    </td>
                    <% @sched2.each do |handle| %>
                      <td><%= handle.grade %> - <%= handle.sec %></td>
                    <% end %>
                </tr>
                <tr>
                    <td>
                        <% begin %>
                        <%= @sched3.first.schedule_time %>
                        <% rescue %>
                        <% end %>
                    </td>
                    <% @sched3.each do |handle| %>
                      <td><%= handle.grade %> - <%= handle.sec %></td>
                    <% end %>
                </tr>
                <tr>
                    <td>
                        <% begin %>
                        <%= @sched4.first.schedule_time %>
                        <% rescue %>
                        <% end %>
                    </td>
                    <td colspan="5">Recess</td>
                </tr>
                <tr>
                    <td>
                        <% begin %>
                        <%= @sched5.first.schedule_time %>
                        <% rescue %>
                        <% end %>
                    </td>
                    <% @sched5.each do |handle| %>
                      <td><%= handle.grade %> - <%= handle.sec %></td>
                    <% end %>
                </tr>
                <tr>
                    <td>
                        <% begin %>
                        <%= @sched6.first.schedule_time %>
                        <% rescue %>
                        <% end %>
                    </td>
                    <% @sched6.each do |handle| %>
                      <td><%= handle.grade %> - <%= handle.sec %></td>
                    <% end %>
                </tr>
                <tr>
                    <td>
                        <% begin %>
                        <%= @sched7.first.schedule_time %>
                        <% rescue %>
                        <% end %>
                    </td>
                    <% @sched7.each do |handle| %>
                      <td><%= handle.grade %> - <%= handle.sec %></td>
                    <% end %>
                </tr>
                <tr>
                    <td>
                        <% begin %>
                        <%= @sched8.first.schedule_time %>
                        <% rescue %>
                        <% end %>
                    </td>
                    <td>Lunch Break</td>
                    <td>Lunch Break</td>
                    <td>Lunch Break</td>
                    <td>Lunch Break</td>
                    <td>Lunch Break</td>
                </tr>
                <tr>
                    <td>
                        <% begin %>
                        <%= @sched9.first.schedule_time %>
                        <% rescue %>
                        <% end %>
                    </td>
                    <% @sched9.each do |handle| %>
                      <td><%= handle.grade %> - <%= handle.sec %></td>
                    <% end %>
                </tr>
                <tr>
                    <td>
                        <% begin %>
                        <%= @sched10.first.schedule_time %>
                        <% rescue %>
                        <% end %>
                    </td>
                    <% @sched10.each do |handle| %>
                      <td><%= handle.grade %> - <%= handle.sec %></td>
                    <% end %>
                </tr>
                <tr>
                    <td>
                        <% begin %>
                        <%= @sched11.first.schedule_time %>
                        <% rescue %>
                        <% end %>
                    </td>
                    <% @sched11.each do |handle| %>
                      <td><%= handle.grade %> - <%= handle.sec %></td>
                    <% end %>
                </tr>
                <tr>
                    <td>
                        <% begin %>
                        <%= @sched12.first.schedule_time %>
                        <% rescue %>
                        <% end %>
                    </td>
                    <% @sched12.each do |handle| %>
                      <td><%= handle.grade %> - <%= handle.sec %></td>
                    <% end %>
                </tr>
                <tr>
                    <td>
                        <% begin %>
                        <%= @sched13.first.schedule_time %>
                        <% rescue %>
                        <% end %>
                    </td>
                    <% @sched13.each do |handle| %>
                      <td><%= handle.grade %> - <%= handle.sec %></td>
                    <% end %>
                </tr>
            </table>
            <a class="btn btn-primary" href="<%= session[:user]["access"] == 1 ? "/schedules" : "/main" %>">
                <span class="glyphicon glyphicon-arrow-left"></span> Back</a>
        </div>
    </div>
</div>

app/views/schedules/student_show.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
            <p id="notice"><%= notice %></p>
            <h1 class="page-header">
            <a class="btn btn-primary pull-right" href="<%= session[:user]["access"] == 1 ? "/schedules" : "/main" %>">
                <span class="glyphicon glyphicon-arrow-left"></span> Back</a>
            Schedule</h1>
            <form id="school_year_form" method="get" class="hidden" action="/schedules/student/<%= params[:year_level_id] %>/<%= params[:section_id] %>" style="width: 150px;">
                <select class="form-control" id="school_year" name="school_year">
                    <% (Time.now + 1.year).year.downto(2014).each do |yr| %>
                    <option <%= 'selected' if params[:school_year] == (yr-1).to_s + "-" + yr.to_s %>><%= (yr-1).to_s + "-" + yr.to_s %></option>
                    <% end %>
                </select>
            </form>
            <table class="table table-bordered table-striped">
                <tr>
                    <td><strong>Time</strong></td>
                    <td><strong>Monday</strong></td>
                    <td><strong>Tuesday</strong></td>
                    <td><strong>Wednesday</strong></td>
                    <td><strong>Thursday</strong></td>
                    <td><strong>Friday</strong></td>
                </tr>
                <tr>
                    <td>
                        <% begin %>
                        <%= @sched1.first.schedule_time %>
                        <% rescue %>
                        <% end %>
                    </td>
                    <td>Flag Ceremony</td>
                    <td>Flag Ceremony</td>
                    <td>Flag Ceremony</td>
                    <td>Flag Ceremony</td>
                    <td>Flag Ceremony</td>
                </tr>
                <tr>
                    <td>
                        <% begin %>
                        <%= @sched2.first.schedule_time %>
                        <% rescue %>
                        <% end %>
                    </td>
                    <% @sched2.each do |handle| %>
                      <td><%= handle.subject %> - <%= handle.room %></td>
                    <% end %>
                </tr>
                <tr>
                    <td>
                        <% begin %>
                        <%= @sched3.first.schedule_time %>
                        <% rescue %>
                        <% end %>
                    </td>
                    <% @sched3.each do |handle| %>
                      <td><%= handle.subject %> - <%= handle.room %></td>
                    <% end %>
                </tr>
                <tr>
                    <td>
                        <% begin %>
                        <%= @sched3.first.schedule_time[8..13] %> - 
                        <%= @sched5.first.schedule_time[0..4] %>
                        <% rescue %>
                        <% end %>
                    </td>
                    <td>Recess</td>
                    <td>Recess</td>
                    <td>Recess</td>
                    <td>Recess</td>
                    <td>Recess</td>
                </tr>
                <tr>
                    <td>
                        <% begin %>
                        <%= @sched5.first.schedule_time %>
                        <% rescue %>
                        <% end %>
                    </td>
                    <% @sched5.each do |handle| %>
                      <td><%= handle.subject %> - <%= handle.room %></td>
                    <% end %>
                </tr>
                <tr>
                    <td>
                        <% begin %>
                        <%= @sched6.first.schedule_time %>
                        <% rescue %>
                        <% end %>
                    </td>
                    <% @sched6.each do |handle| %>
                      <td><%= handle.subject %> - <%= handle.room %></td>
                    <% end %>
                </tr>
                <tr>
                    <td>
                        <% begin %>
                        <%= @sched7.first.schedule_time %>
                        <% rescue %>
                        <% end %>
                    </td>
                    <% @sched7.each do |handle| %>
                      <td><%= handle.subject %> - <%= handle.room %></td>
                    <% end %>
                </tr>
                <tr>
                    <td>
                        <% begin %>
                        <%= @sched7.first.schedule_time[8..13] %> - 
                        <%= @sched9.first.schedule_time[0..4] %>
                        <% rescue %>
                        <% end %>
                    </td>
                    <td>Lunch Break</td>
                    <td>Lunch Break</td>
                    <td>Lunch Break</td>
                    <td>Lunch Break</td>
                    <td>Lunch Break</td>
                </tr>
                <tr>
                    <td>
                        <% begin %>
                        <%= @sched9.first.schedule_time %>
                        <% rescue %>
                        <% end %>
                    </td>
                    <% @sched9.each do |handle| %>
                      <td><%= handle.subject %> - <%= handle.room %></td>
                    <% end %>
                </tr>
                <tr>
                    <td>
                        <% begin %>
                        <%= @sched10.first.schedule_time %>
                        <% rescue %>
                        <% end %>
                    </td>
                    <% @sched10.each do |handle| %>
                      <td><%= handle.subject %> - <%= handle.room %></td>
                    <% end %>
                </tr>
                <tr>
                    <td>
                        <% begin %>
                        <%= @sched11.first.schedule_time %>
                        <% rescue %>
                        <% end %>
                    </td>
                    <% @sched11.each do |handle| %>
                      <td><%= handle.subject %> - <%= handle.room %></td>
                    <% end %>
                </tr>
                <tr>
                    <td>
                        <% begin %>
                        <%= @sched12.first.schedule_time %>
                        <% rescue %>
                        <% end %>
                    </td>
                    <% @sched12.each do |handle| %>
                      <td><%= handle.subject %> - <%= handle.room %></td>
                    <% end %>
                </tr>
                <tr>
                    <td>
                        <% begin %>
                        <%= @sched13.first.schedule_time %>
                        <% rescue %>
                        <% end %>
                    </td>
                    <% @sched13.each do |handle| %>
                      <td><%= handle.subject %> - <%= handle.room %></td>
                    <% end %>
                </tr>
            </table>
        </div>
    </div>
</div>