config/routes.rb
Rails.application.routes.draw do

  
  get '/get-sections' => 'students#get_sections'
  get '/save-grade' => 'grades#save_grade'

  resources :sections
  resources :rooms
  get '/logout' => 'home#logout'
  post '/login' => 'home#login'
  resources :teachers
  resources :positions
  resources :events
  resources :users
  resources :schedules
  resources :subjects
  get '/schedules/student/:year_level_id/:section_id' => 'schedules#student_show'
  post '/change-password' => 'users#change_password'
  get '/change-password' => 'home#change_password'
  get '/grades' => 'grades#index'
  get '/grades/show/:id' => 'grades#show'
  get '/main' => 'home#main'
  get '/schedule' => 'home#schedule'
  get '/students-main' => 'home#students_main'
  post '/pay' => 'payments#pay'
  get '/payform/:student_id' => 'payments#payform'
  get '/payments/print/:or_number' => 'payments#print'
  get '/payments' => 'payments#index'
  get '/payments/:student_id' => 'payments#history'
  get '/get-payment' => 'payments#get_payment'
  
  resources :students
  root 'home#index'
  

end

app/models/event.rb
class Event < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	mount_uploader :image2, ImageUploader
	mount_uploader :image3, ImageUploader
	mount_uploader :image4, ImageUploader
	mount_uploader :image5, ImageUploader
	mount_uploader :image6, ImageUploader
	mount_uploader :image7, ImageUploader
	mount_uploader :image8, ImageUploader
	mount_uploader :image9, ImageUploader
	#attr_accessor :folder_name, :fn
end

app/models/grade.rb
class Grade < ActiveRecord::Base
  belongs_to :student
end

app/models/payment.rb
class Payment < ActiveRecord::Base
	belongs_to :student
end

app/models/position.rb
class Position < ActiveRecord::Base
    has_one :teacher
end

app/models/room.rb
class Room < ActiveRecord::Base
	has_one :teacher
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :year_level
  belongs_to :section
  belongs_to :teacher

  def self.index_fields
    joins(:position, :subject, :room).
    select("teachers.id, teachers.teacherid, teachers.first_name,
            teachers.last_name,
            positions.description pos,
            subjects.description sub,
            rooms.description rm")
  end
end

app/models/section.rb
class Section < ActiveRecord::Base
end

app/models/student.rb
# class Student < ActiveRecord::Base
#     has_many :student_year_sections
#     has_many :payments

#     def self.index_fields
#         joins(:student_year_sections)
#          .select("students.id, 
#                           students.student_id, 
#                           students.fname, 
#                           students.mname, 
#                           students.lname, 
#                           students.address,
#                           students.status, max(student_year_sections.school_year) school_year")
#         .group("students.id")
                            
#     end
# end
class Student < ActiveRecord::Base
    has_many :student_year_sections
    has_many :payments

    def self.index_fields
        joins(:student_year_sections => [:year_level])
         .select("students.id, 
                          students.student_id, 
                          students.fname, 
                          students.mname, 
                          students.lname, 
                          students.address,
                          students.status, 
                          year_levels.description grade,
                          student_year_sections.year_level_id,
                          student_year_sections.section_id")
                            
    end
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_one :teacher
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  belongs_to :position
  belongs_to :subject
  belongs_to :room
  has_many :schedules

  def self.index_fields
    joins(:position, :subject, :room).
    select("teachers.id, teachers.teacherid, teachers.first_name,
            teachers.last_name,
            positions.description pos,
            subjects.description sub,
            rooms.description rm")
  end

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
     validates :user_name, uniqueness: {message: "already exist!" }
     validates :user_pass, presence: true
end

app/models/year_level.rb
class YearLevel < ActiveRecord::Base
    has_one :student_year_section
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.index_fields.paginate(:page => params[:page], :per_page => 20)
    if params[:txt_search]
        @teachers = Teacher.index_fields.where("teachers.first_name ilike ?", "#{params[:txt_search]}%").paginate(:page => params[:page], :per_page => 20) if params[:searchby] == "fname"
        @teachers = Teacher.index_fields.where("teachers.last_name ilike ?", "#{params[:txt_search]}%").paginate(:page => params[:page], :per_page => 20) if params[:searchby] == "lname"
    end
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
    @user = User.new
    autogenerate_id
  end

  # GET /teachers/1/edit
  def edit
    @user = User.find(@teacher.user_id)
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)
    @user = User.new(:user_name => params[:user_name], :user_pass => params[:user_pass], :status => 'Active', :access => 2)

    respond_to do |format|
      if @user.save
        @teacher.user_id = @user.id
        @teacher.save
        format.html { redirect_to "/teachers", notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html {redirect_to "/teachers/new", notice: "Error: Username already exist!"}
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to "/teachers", notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def autogenerate_id
    year_now = Time.now.year.to_s
    get_last_teacher_id = Teacher.where("teacherid ilike ?", year_now + "ASF%").count + 1
    @teacher_id = year_now + "ASF" + get_last_teacher_id.to_s.rjust(4, '0')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:first_name, :last_name, :position_id, :user_id, :subject_id, :room_id, :teacherid, :philhealth, :tin, :sss, :gender, :address, :contact_number, :image)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/teachers/_form.html.erb
<%= form_for (@teacher), :html => {:multipart => true} do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-sm-12">
    <img src="<%= @teacher.image %>" width="200px">
    <div class="form-group">
      <%= f.label :image %>
      <%= f.file_field :image, :class => "form-control" %>
    </div>
  </div>
  <div class="col-sm-4">
    <div class="form-group">
      <label for="teacher_teacherid">Teacher ID</label>
      <input class="form-control" type="text" name="teacher[teacherid]" id="teacher_teacherid" value="<%= params[:id] ? @teacher.teacherid : @teacher_id %>">
    </div>
  </div>
  <div class="col-sm-4">
    <div class="form-group">
      <label for="user_name">User name</label>
      <input class="form-control" type="text" name="user_name" id="user_name" value="<%= @user.user_name %>">
    </div>
  </div>
  <div class="col-sm-4">
    <div class="form-group">
      <label for="user_pass">User pass</label>
      <input class="form-control" type="password" name="user_pass" id="user_pass" value="<%= params[:id] ? @user.user_pass : @teacher_id %>">
    </div>
  </div>
  <div class="col-sm-4">
    <div class="form-group">
      <%= f.label :philhealth %>
      <%= f.text_field :philhealth, :class => "form-control" %>
    </div>
  </div>
  <div class="col-sm-4">
    <div class="form-group">
      <%= f.label :tin %>
      <%= f.text_field :tin, :class => "form-control" %>
    </div>
  </div>
  <div class="col-sm-4">
    <div class="form-group">
      <%= f.label :sss %>
      <%= f.text_field :sss, :class => "form-control" %>
    </div>
  </div>
  <div class="col-sm-4">
    <div class="form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, :class => "form-control" %>
    </div>
  </div>
  <div class="col-sm-4">
    <div class="form-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, :class => "form-control" %>
    </div>
  </div>
  <div class="col-sm-4">
    <div class="form-group">
      <label for="teacher_gender">Gender</label>
      <select class="form-control" name="teacher[gender]" id="teacher_gender">
        <option value="Male">Male</option>
        <option value="Female" <%= 'selected' if @teacher.gender == "Female" %>>Female</option>
      </select>
    </div>
  </div>
  <div class="col-sm-8">
    <div class="form-group">
      <%= f.label :address %>
      <%= f.text_field :address, :class => "form-control" %>
    </div>
  </div>
  <div class="col-sm-4">
    <div class="form-group">
      <%= f.label :contact_number %>
      <%= f.text_field :contact_number, :class => "form-control" %>
    </div>
  </div>
  <div class="col-sm-4">
    <div class="form-group">
      <%= f.label "Position" %>
      <%= select("teacher", "position_id", Position.all.collect {|s| [s.description, s.id]}, {}, :class => "form-control", :name => "teacher[position_id]")%>
    </div>
  </div>
  <div class="col-sm-4">
    <div class="form-group">
      <%= f.label "Subject" %>
      <%= select("teacher", "subject_id", Subject.all.collect {|s| [s.description, s.id]}, {}, :class => "form-control", :name => "teacher[subject_id]")%>
    </div>
  </div>
  <div class="col-sm-4">
    <div class="form-group">
      <%= f.label "Room" %>
      <%= select("teacher", "room_id", Room.all.collect {|r| [r.description, r.id]}, {}, :class => "form-control", :name => "teacher[room_id]")%>
    </div>
  </div>
  <div class="col-sm-12">
  <button class="btn btn-md btn-primary">
      Save
  </button>
  <a class="btn btn-primary" href="/teachers">
    <span class="glyphicon glyphicon-arrow-left"></span> Back
  </a>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<div class="container-fluid"><div class="row"><div class="col-sm-10 col-sm-offset-1">
<h1 class="page-header">Edit Teacher</h1>
<div class="panel panel-default">
	<div class="panel-heading">Teacher's Profile</div>
	<div class="panel-body">
		<%= render 'form' %>
	</div>
</div>
</div></div></div>

app/views/teachers/index.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-10 col-sm-offset-1">
			<% if notice %>
				<div class="alert alert-success"><%= notice %></div>
			<% end %>
			
			<h1 class="page-header">Teachers
				<a href="/teachers/new" class="btn btn-primary pull-right">
				<span class="glyphicon glyphicon-user"></span> Add Teacher
				</a>
			</h1>
			<div class="row" style="margin-bottom: 10px;">
			<form>
              <div class="col-sm-3">
               <label>Search by:</label>
                <select class="form-control" name="searchby">
                  <option value="fname">First Name</option>
                  <option value="lname" <%= "selected" if params[:searchby] == "lname" %>>Last Name</option>
                </select>
              </div>
              <div class="col-sm-3">
                <label>Search text:</label>
                <input type="text" class="form-control" name="txt_search" value="<%= params[:txt_search] if params[:txt_search] %>">
              </div>
              <div class="col-sm-2" style="margin-top: 25px;">
                <button class="btn btn-primary" type="submit">
                    <span class="glyphicon glyphicon-search"></span> Search
                </button>
              </div>
              </form>
			</div>
			<table class="table table-bordered table-striped">
				<thead>
					<tr>
						<th>Teacher ID</th>
						<th>First name</th>
						<th>Last name</th>
						<th>Position</th>
						<th>Subject</th>
						<th>Room</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @teachers.each do |teacher| %>
					<tr>
						<td><%= teacher.teacherid %></td>
						<td><%= teacher.first_name %></td>
						<td><%= teacher.last_name %></td>
						<td><%= teacher.pos %></td>
						<td><%= teacher.sub %></td>
						<td><%= teacher.rm %></td>
						<td>
                			<%= link_to edit_teacher_path(teacher), :class => "btn btn-sm btn-primary" do %>
								Edit
							<% end %>
            			</td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/teachers/new.html.erb
<div class="container-fluid"><div class="row"><div class="col-sm-10 col-sm-offset-1">
<% if notice %>
<div class="alert alert-danger"><%= notice %></div>
<% end %>
<h1 class="page-header">New Teacher</h1>
<div class="panel panel-default">
	<div class="panel-heading">Teacher's Profile</div>
	<div class="panel-body">
		<%= render 'form' %>
	</div>
</div>
</div></div></div>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @teacher.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @teacher.last_name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @teacher.position %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>